# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: ukneutron # jekyll-seo-tag > Owners twitter username
author: ukneutron # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: ukneutron # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/ukneutron
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: News # Needed for Siteleaf
    output: true
    #description: "" # The post list page content
    feature_image: "/assets/isis.png"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Neutron Scattering Group" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo_nsg_2023.png" # Site logo, also used in jekyll-seo-tag
description: "Representing UK users of neutron scattering" # Site description and default description, also used in jekyll-seo-tag
url: "https://ukneutron.org" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/ukneutron/ukneutron.github.io"
email: "a.r.mccluskey@bath.ac.uk"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
#avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
google_analytics: 'UA-28510117-1'
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  About: /about/
  Prizes: /prizes/
  Resources: /resources/
  News: /blog/
  Committee: /committee/
  Join: /join/
  Search: /search/
  #Fork Alembic: https://github.com/daviddarnes/alembic

navigation_footer:
  Created by Andrew McCluskey & Sanghamitra Mukhopadhyay:

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/ukneutron
  #LinkedIn: https://www.linkedin.com/in/daviddarnes
  #Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/ukneutron
  #link: https://darn.es
  #RSS: /feed.xml

#sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
#  Twitter: "#0d94e7"
#  facebook: "#3B5998"
#  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
